name: 'Flyway Hub Migration Test'
branding:
  color: purple
  icon: database
description: 'Test Flyway database migrations on Flyway Hub'
inputs:
  projectName:
    description: 'The name of the Flyway Hub project to test'
    required: true
  engine:
    description: 'The database engine that migrations should run against'
    required: true
  flywayConfPath:
    description: 'The path to the flyway conf to use when running this migration test'
    required: false
  databaseName:
    description: 'The custom database to create and run the flyway migrations against'
    required: false
  migrationDirs:
    description: 'The directories containing the migration scripts to run'
    required: true

outputs: {}

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.projectName }}
    - ${{ inputs.flywayConfPath }}
    - ${{ inputs.databaseName }}
    - ${{ inputs.engine }}
    - ${{ inputs.migrationDirs }}
