name: 'Flyway Hub Migration Test'
branding:
  color: purple
  icon: database
description: 'Test Flyway database migrations on Flyway Hub'
inputs:
  projectId:
    description: 'The id of the Flyway Hub project to test'
    required: true
  flywayConfPath:
    description: 'The path to the flyway conf to use when running this migration test'
    required: false
  databaseName:
    description: 'The custom database to create and run the flyway migrations against'
    required: false


outputs: {}

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.projectId }}
    - ${{ inputs.flywayConfPath }}
    - ${{ inputs.databaseName }}
